'use client';
import { useState } from 'react';
import { useAuth, pageLinks } from '../../components/auth/AuthProvider';
import { apiRequest } from '../../lib/api';
import { roles, type Permissions } from '../../../shared/access.types';
import Icon from '../../components/common/Icon';
function PermissionForm({ initial }: { initial: Permissions }) {
  const { refresh } = useAuth(); const [permissions, setPermissions] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function save() { setBusy(true); setError(''); setMessage(''); try { await apiRequest('/settings/permissions', { permissions }); await refresh(); setMessage('Permissions saved. API restrictions apply immediately; open pages refresh within 15 seconds.'); } catch (e) { setError(e instanceof Error ? e.message : 'Save failed.'); } finally { setBusy(false); } }
  return <><div className="table-scroll"><table><thead><tr><th>Role</th>{pageLinks.map(link => <th key={link.page}>{link.label}</th>)}</tr></thead><tbody>{roles.map(role => <tr key={role}><th>{role}</th>{pageLinks.map(({ page, label }) => <td key={page}><input type="checkbox" aria-label={`${role}: ${label}`} checked={permissions[role][page]} disabled={busy || page === 'config' || page === 'permissions'} onChange={e => setPermissions({ ...permissions, [role]: { ...permissions[role], [page]: e.target.checked } })} /></td>)}</tr>)}</tbody></table></div><p className="muted">Configuration and permission management remain MD-only. Page access does not grant another role’s payment actions: Employees create/resubmit, Managers review Manager-pending requests, and MD reviews MD-pending requests.</p>{error && <p className="notice error" role="alert">{error}</p>}{message && <p className="notice success" role="status">{message}</p>}<button className="primary" disabled={busy} onClick={save}>{busy ? 'Saving…' : 'Save permissions'}</button></>;
}
export default function PermissionsPage() { const { session } = useAuth(); return session ? <main className="settings-page"><p className="eyebrow">ADMINISTRATION / ACCESS CONTROL</p><h1>Roles &amp; permissions</h1><p className="muted">Give each role access to the pages it needs.</p><section className="settings-card"><div className="settings-section-heading"><span className="panel-icon"><Icon name="shield" /></span><div><h2>Page access matrix</h2><p>Checked means access is allowed. Administrative permissions are locked.</p></div><span className="role-chip role-md">MD only</span></div><PermissionForm initial={session.permissions} /></section></main> : null; }
